# Generated by Django 5.0.1 on 2024-02-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheduler', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='status',
            field=models.CharField(choices=[('start', 'Запущена'), ('finish', 'Отправлено'), ('created', 'Создана')], max_length=50, verbose_name='статус'),
        ),
    ]
