# Generated by Django 5.0.1 on 2024-02-16 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheduler', '0013_rename_mail_to_mail_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mail',
            options={'ordering': ('start_date',), 'permissions': [('set_is_active', 'Может отключать рассылку')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
