# Generated by Django 5.0.1 on 2024-02-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheduler', '0014_alter_mail_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mail',
            options={'ordering': ('start_date',), 'permissions': [('set_is_activated', 'Может отключать рассылку')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AlterField(
            model_name='mail',
            name='interval',
            field=models.CharField(choices=[('once_a_day', 'ежедневно'), ('once_a_week', 'раз в неделю'), ('once_a_month', 'раз в месяц')], default='разовая', max_length=50, verbose_name='интервал'),
        ),
    ]
