# Generated by Django 5.0.1 on 2024-02-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheduler', '0015_alter_mail_options_alter_mail_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='interval',
            field=models.CharField(choices=[('once_a_day', 'once_a_day'), ('once_a_week', 'once_a_week'), ('once_a_month', 'once_a_month')], default='разовая', max_length=50, verbose_name='интервал'),
        ),
    ]
