# Generated by Django 5.0.1 on 2024-02-16 20:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheduler', '0016_alter_mail_interval'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название рассылки')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='время старта рассылки')),
                ('next_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='время следующей рассылки')),
                ('end_date', models.DateTimeField(verbose_name='время окончания рассылки')),
                ('interval', models.CharField(choices=[('once_a_day', 'once_a_day'), ('once_a_week', 'once_a_week'), ('once_a_month', 'once_a_month')], default='разовая', max_length=50, verbose_name='периодичность')),
                ('status', models.CharField(choices=[('start', 'start'), ('finish', 'finish'), ('created', 'created')], help_text='Выберите Создана или Завершена', max_length=50)),
                ('is_activated', models.BooleanField(default=True, verbose_name='действующая')),
                ('client', models.ManyToManyField(to='sheduler.client', verbose_name='кому')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sheduler.message', verbose_name='сообщение')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец рассылки')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
                'ordering': ('start_date',),
                'permissions': [('set_is_activated', 'Может отключать рассылку')],
            },
        ),
        migrations.AlterField(
            model_name='logs',
            name='mailing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sheduler.mailing', verbose_name='рассылка'),
        ),
        migrations.DeleteModel(
            name='Mail',
        ),
    ]
